'use client';

import type { Metadata } from 'next';

interface SeoInspectorProps {
  metadata: Metadata;
  structuredData?: any;
}

export default function SeoInspector({ metadata, structuredData }: SeoInspectorProps) {
  return (
    <div className="seo-inspector">
      <h3>🔍 Live SEO Inspector</h3>
      <p style={{ color: '#718096', marginBottom: '1rem' }}>
        This shows the SEO metadata generated by M-SEO for this page
      </p>

      <div className="seo-section">
        <h4>Basic Meta Tags</h4>
        <div className="meta-list">
          <div className="meta-item">
            <strong>Title:</strong> {metadata.title?.toString() || 'N/A'}
          </div>
          <div className="meta-item">
            <strong>Description:</strong> {metadata.description || 'N/A'}
          </div>
        </div>
      </div>

      {metadata.openGraph && (
        <div className="seo-section">
          <h4>Open Graph Tags</h4>
          <div className="meta-list">
            {Object.entries(metadata.openGraph).map(([key, value]) => (
              <div key={key} className="meta-item">
                <strong>og:{key}:</strong> {typeof value === 'object' ? JSON.stringify(value) : String(value)}
              </div>
            ))}
          </div>
        </div>
      )}

      {metadata.twitter && (
        <div className="seo-section">
          <h4>Twitter Card Tags</h4>
          <div className="meta-list">
            {Object.entries(metadata.twitter).map(([key, value]) => (
              <div key={key} className="meta-item">
                <strong>twitter:{key}:</strong> {String(value)}
              </div>
            ))}
          </div>
        </div>
      )}

      {structuredData && (
        <div className="seo-section">
          <h4>Structured Data (JSON-LD)</h4>
          <pre>{JSON.stringify(structuredData, null, 2)}</pre>
        </div>
      )}
    </div>
  );
}
